# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080
    vm1.vm.network "forwarded_port", guest: 22, host: 2222
  end
  
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "forwarded_port", guest: 80, host: 8081
    vm2.vm.network "forwarded_port", guest: 22, host: 2223
  end
end
